In [1]:
import os
import sys
import matplotlib

import pandas as pd
import numpy as np
import anndata as ad
import scanpy as sc
import matplotlib.pyplot as plt

import tacco as tc

# Variables

In [2]:
data_object_dir = '/rfs/project/rfs-iCNyzSAaucw/kk837/data_objects/Foetal/Xenium'
!ls {data_object_dir}

C194-HEA-0-FFPE-1_5K_filtered_lognorm.h5ad
C194-HEA-0-FFPE-1_5K_filtered_raw.h5ad
C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_Cardiomyocytes_annotations.csv
C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_celltype-sel_raw.h5ad
C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_MyeloidCells_mixture_annotations.csv
C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_NeuralCells_mixture_annotations.csv
C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_raw.h5ad
Hst45-HEA-0-FFPE-1_5K_filtered_lognorm.h5ad
Hst45-HEA-0-FFPE-1_5K_filtered_raw.h5ad
subsets_archive
TACCO

# Read in reference data

In [3]:
ref = sc.read_h5ad(f'{data_object_dir}/TACCO/reference_raw.h5ad')
ref

AnnData object with n_obs × n_vars = 367709 × 5001
    obs: 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'n_genes', 'tissue_block_id', 'celltypist_coarse', 'conf_score_coarse', 'celltypist_coarse_fin', 'celltypist_coarse2midmod', 'conf_score_coarse2midmod', 'celltypist_mid_fin', 'celltypist_midmod2fine', 'conf_score_midmod2fine', 'pca_harmony_leiden_0.2', 'pca_harmony_leiden_0.3', 'pca_harmony_leiden_0.4', 'pca_harmony_leiden_0.5', 'pca_harmony_leiden_0.8', 'pca_harmony_leiden_1.0', 'pca_harmony_leiden_1.5', 'pca_harmony_leiden_2.0', 'pca_harmony_leiden_3.0', 'multi_celltypes_coarse', 'fine_grain_12Jun2025', 'sliding_window_assignment', 'window_col', 'window_row', 'globalX', 'globalY', 'tt_prediction', 'coarse_grain_pre', 'coarse_grain_pre_2', 'reference_type', 'latent_RT_efficiency', 'latent_cell_probability', 'latent_scale', 'sangerID', 'combinedID', 'donor', 'region', 'age', 'facility', 'cell_or_nuclei', 'modality', 'kit_10x', 'scrublet_score', 'doublet_pval', 'doublet_bh_pval', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'HB_score', 'donor_by_library-prep', 'multiplexed', 'SOC | status', 'SOC | log_prob_singleton', 'SOC | log_prob_doublet', 'batch_key', '_scvi_batch', 'FACSgate', 'fine_grain', 'mid_grain', 'coarse_grain', 'sex', 'week', 'trimester', 'heart_or_greatvessels', 'cycling', 'S_score', 'G2M_score', 'phase', '_scvi_labels', 'stress_score', 'hb1_score', 'mid_grain_mod', 'reference_celltype'
    var: 'gene_ids-0', 'feature_types-0', 'genome-0', 'n_cells_by_counts-0-0', 'mean_counts-0-0', 'log1p_mean_counts-0-0', 'pct_dropout_by_counts-0-0', 'total_counts-0-0', 'log1p_total_counts-0-0', 'n_cells_by_counts-1-0', 'mean_counts-1-0', 'log1p_mean_counts-1-0', 'pct_dropout_by_counts-1-0', 'total_counts-1-0', 'log1p_total_counts-1-0', 'gene_name_scRNA-0-1', 'gene_id-1'

# Read in query data

In [4]:
que = sc.read_h5ad(f'{data_object_dir}/C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_celltype-sel_raw.h5ad')
que

AnnData object with n_obs × n_vars = 341592 × 5001
    obs: 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'n_genes', 'tissue_block_id', 'celltypist_coarse', 'conf_score_coarse', 'celltypist_coarse_fin', 'celltypist_coarse2midmod', 'conf_score_coarse2midmod', 'celltypist_mid_fin', 'celltypist_midmod2fine', 'conf_score_midmod2fine', 'pca_harmony_leiden_0.2', 'pca_harmony_leiden_0.3', 'pca_harmony_leiden_0.4', 'pca_harmony_leiden_0.5', 'pca_harmony_leiden_0.8', 'pca_harmony_leiden_1.0', 'pca_harmony_leiden_1.5', 'pca_harmony_leiden_2.0', 'pca_harmony_leiden_3.0', 'multi_celltypes_coarse', 'fine_grain_12Jun2025', 'sliding_window_assignment', 'window_col', 'window_row', 'globalX', 'globalY', 'tt_prediction', 'coarse_grain_pre', 'coarse_grain_pre_2'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts-0', 'mean_counts-0', 'log1p_mean_counts-0', 'pct_dropout_by_counts-0', 'total_counts-0', 'log1p_total_counts-0', 'n_cells_by_counts-1', 'mean_counts-1', 'log1p_mean_counts-1', 'pct_dropout_by_counts-1', 'total_counts-1', 'log1p_total_counts-1'
    uns: 'celltypist_coarse2midmod_colors', 'celltypist_coarse_colors', 'celltypist_mid_fin_colors', 'coarse_grain_pre_2_colors', 'dendrogram_pca_harmony_leiden_1.0', 'fine_grain_12Jun2025_colors', 'multi_celltypes_coarse_colors', 'pca', 'pca_harmony', 'pca_harmony_leiden_0.2', 'pca_harmony_leiden_0.2_colors', 'pca_harmony_leiden_0.3', 'pca_harmony_leiden_0.3_colors', 'pca_harmony_leiden_0.4', 'pca_harmony_leiden_0.4_colors', 'pca_harmony_leiden_0.5', 'pca_harmony_leiden_0.5_colors', 'pca_harmony_leiden_0.8', 'pca_harmony_leiden_0.8_colors', 'pca_harmony_leiden_1.0', 'pca_harmony_leiden_1.0_colors', 'pca_harmony_leiden_1.5', 'pca_harmony_leiden_1.5_colors', 'pca_harmony_leiden_2.0', 'pca_harmony_leiden_2.0_colors', 'pca_harmony_leiden_3.0', 'pca_harmony_leiden_3.0_colors', 'tissue_block_id_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap_pca_harmony', 'spatial'
    varm: 'PCs'
    obsp: 'pca_harmony_connectivities', 'pca_harmony_distances'

# Step 1: spot deconvolution

In [5]:
%%time
tc.tl.annotate(
    que,
    ref, 
    'reference_celltype',
    result_key='TACCO',
    multi_center=10, # how many subpopulation would you expect in a cell type label
    reconstruction_key='rec',
    counts_location=('X'),
    assume_valid_counts=True
)

Starting preprocessing
Annotation profiles were not found in `reference.varm["reference_celltype"]`. Constructing reference profiles with `tacco.preprocessing.construct_reference_profiles` and default arguments...
Finished preprocessing in 15.2 seconds.
Starting annotation of data with shape (341592, 5001) and a reference of shape (367709, 5001) using the following wrapped method:
+- platform normalization: platform_iterations=0, gene_keys=reference_celltype, normalize_to=adata
   +- multi center: multi_center=10 multi_center_amplitudes=True
      +- bisection boost: bisections=4, bisection_divisor=3
         +- core: method=OT annotation_prior=None
mean,std( rescaling(gene) )  0.8366071682696716 0.424433324298815
bisection run on 1
bisection run on 0.6666666666666667
bisection run on 0.4444444444444444
bisection run on 0.2962962962962963
bisection run on 0.19753086419753085
bisection run on 0.09876543209876543
Finished annotation in 144.08 seconds.
CPU times: user 7min 56s, sys: 21 s, total: 8min 17s
Wall time: 2min 39s

AnnData object with n_obs × n_vars = 341592 × 5001
    obs: 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'n_genes', 'tissue_block_id', 'celltypist_coarse', 'conf_score_coarse', 'celltypist_coarse_fin', 'celltypist_coarse2midmod', 'conf_score_coarse2midmod', 'celltypist_mid_fin', 'celltypist_midmod2fine', 'conf_score_midmod2fine', 'pca_harmony_leiden_0.2', 'pca_harmony_leiden_0.3', 'pca_harmony_leiden_0.4', 'pca_harmony_leiden_0.5', 'pca_harmony_leiden_0.8', 'pca_harmony_leiden_1.0', 'pca_harmony_leiden_1.5', 'pca_harmony_leiden_2.0', 'pca_harmony_leiden_3.0', 'multi_celltypes_coarse', 'fine_grain_12Jun2025', 'sliding_window_assignment', 'window_col', 'window_row', 'globalX', 'globalY', 'tt_prediction', 'coarse_grain_pre', 'coarse_grain_pre_2'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts-0', 'mean_counts-0', 'log1p_mean_counts-0', 'pct_dropout_by_counts-0', 'total_counts-0', 'log1p_total_counts-0', 'n_cells_by_counts-1', 'mean_counts-1', 'log1p_mean_counts-1', 'pct_dropout_by_counts-1', 'total_counts-1', 'log1p_total_counts-1'
    uns: 'celltypist_coarse2midmod_colors', 'celltypist_coarse_colors', 'celltypist_mid_fin_colors', 'coarse_grain_pre_2_colors', 'dendrogram_pca_harmony_leiden_1.0', 'fine_grain_12Jun2025_colors', 'multi_celltypes_coarse_colors', 'pca', 'pca_harmony', 'pca_harmony_leiden_0.2', 'pca_harmony_leiden_0.2_colors', 'pca_harmony_leiden_0.3', 'pca_harmony_leiden_0.3_colors', 'pca_harmony_leiden_0.4', 'pca_harmony_leiden_0.4_colors', 'pca_harmony_leiden_0.5', 'pca_harmony_leiden_0.5_colors', 'pca_harmony_leiden_0.8', 'pca_harmony_leiden_0.8_colors', 'pca_harmony_leiden_1.0', 'pca_harmony_leiden_1.0_colors', 'pca_harmony_leiden_1.5', 'pca_harmony_leiden_1.5_colors', 'pca_harmony_leiden_2.0', 'pca_harmony_leiden_2.0_colors', 'pca_harmony_leiden_3.0', 'pca_harmony_leiden_3.0_colors', 'tissue_block_id_colors', 'umap', 'rec'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap_pca_harmony', 'spatial', 'rec', 'TACCO'
    varm: 'PCs', 'rec'
    obsp: 'pca_harmony_connectivities', 'pca_harmony_distances'

In [6]:
que.obsm['TACCO']

reference_celltype,AtrialCardiomyocytes,EndothelialCells,EpicardialCells,LymphoidCells,MesenchymalCells,MyeloidCells,NeuralCells,VentricularCardiomyocytes
C194-HEA-0-FFPE-1_aaaafiob-1,0.000339,2.133923e-05,3.475924e-02,1.384285e-05,9.628719e-01,6.736262e-05,1.149058e-04,0.001813
C194-HEA-0-FFPE-1_aaaajopp-1,0.005728,8.550352e-05,4.920605e-02,9.022435e-03,9.024110e-01,6.295047e-03,9.987709e-06,0.027242
C194-HEA-0-FFPE-1_aaaanald-1,0.001661,3.378865e-05,2.669429e-02,9.339666e-07,9.582528e-01,3.889883e-06,6.701673e-04,0.012683
C194-HEA-0-FFPE-1_aaabdjka-1,0.000053,6.144239e-06,1.578933e-02,6.224639e-08,9.840493e-01,3.669306e-07,3.550096e-06,0.000098
C194-HEA-0-FFPE-1_aaabglmg-1,0.002515,9.611493e-07,1.620641e-02,8.388585e-08,9.812043e-01,3.914323e-06,1.771943e-05,0.000052
...,...,...,...,...,...,...,...,...
Hst45-HEA-0-FFPE-1_oigbenna-1,0.023419,1.301260e-01,5.941236e-04,9.224510e-05,1.364430e-02,5.374312e-05,6.871757e-06,0.832063
Hst45-HEA-0-FFPE-1_oigbmoed-1,0.027221,3.097637e-13,1.126926e-10,2.157865e-11,1.309462e-10,7.629422e-12,1.836565e-12,0.972779
Hst45-HEA-0-FFPE-1_oigcbndd-1,0.010431,1.518322e-07,7.872185e-06,8.913598e-07,3.168801e-05,5.212727e-06,7.563716e-06,0.989516
Hst45-HEA-0-FFPE-1_oigeiifh-1,0.015658,2.660045e-05,1.355248e-04,1.279097e-04,4.132080e-03,7.007149e-04,1.177396e-04,0.979102
Hst45-HEA-0-FFPE-1_oigenchi-1,0.085305,1.339642e-05,3.125826e-02,1.993746e-04,3.517229e-01,1.191626e-03,9.342905e-04,0.529375

# Step 2: split the object

In [7]:
%%time
# splitting
sdata = tc.tl.split_observations(
    que, 
    'rec', 
    map_obs_keys=True, 
    result_key='coarse_grain_tacco',
    counts_location=('X'),
)

scale.....time 143.75154733657837
fuseall...time 61.67194104194641
CPU times: user 5min 21s, sys: 40.1 s, total: 6min 1s
Wall time: 3min 39s

In [8]:
que.obs

,cell_id,x_centroid,y_centroid,transcript_counts,control_probe_counts,genomic_control_counts,control_codeword_counts,unassigned_codeword_counts,deprecated_codeword_counts,total_counts,...,multi_celltypes_coarse,fine_grain_12Jun2025,sliding_window_assignment,window_col,window_row,globalX,globalY,tt_prediction,coarse_grain_pre,coarse_grain_pre_2
C194-HEA-0-FFPE-1_aaaafiob-1,aaaafiob-1,782.026245,1025.860474,754,0,0,0,0,0,754.0,...,No,FibroblastsCOL2A1pos,C194-HEA-0-FFPE-1_window_1170,762.770691,1009.514893,782.026245,1025.860474,Adventitia - GV,MesenchymalCells,MesenchymalCells
C194-HEA-0-FFPE-1_aaaajopp-1,aaaajopp-1,784.114746,1034.308350,145,0,0,0,0,0,145.0,...,No,unassigned,C194-HEA-0-FFPE-1_window_1170,762.770691,1009.514893,784.114746,1034.308350,Adventitia - GV,MesenchymalCells,MesenchymalCells
C194-HEA-0-FFPE-1_aaaanald-1,aaaanald-1,791.200500,1028.298462,569,0,0,0,0,0,569.0,...,No,unassigned,C194-HEA-0-FFPE-1_window_1299,812.770691,1009.514893,791.200500,1028.298462,Adventitia - GV,MesenchymalCells,MesenchymalCells
C194-HEA-0-FFPE-1_aaabdjka-1,aaabdjka-1,819.555664,1032.847168,659,0,0,0,1,0,659.0,...,No,PericardialCellsIntermediate,C194-HEA-0-FFPE-1_window_1299,812.770691,1009.514893,819.555664,1032.847168,Adventitia - GV,MesenchymalCells,MesenchymalCells
C194-HEA-0-FFPE-1_aaabglmg-1,aaabglmg-1,819.384583,1007.732910,83,0,0,0,0,0,83.0,...,NaN,unassigned,C194-HEA-0-FFPE-1_window_1299,812.770691,1009.514893,819.384583,1007.732910,Adventitia - GV,MesenchymalCells,MesenchymalCells
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Hst45-HEA-0-FFPE-1_oigbenna-1,oigbenna-1,2148.711670,3039.862793,342,0,0,0,0,0,342.0,...,Yes,unassigned,Hst45-HEA-0-FFPE-1_window_4932,2130.637722,3035.430790,2148.711670,3039.862793,Ventricle - Compact,unclassified_mixture,unclassified_mixture
Hst45-HEA-0-FFPE-1_oigbmoed-1,oigbmoed-1,2266.702148,2901.389648,350,0,0,0,0,2,350.0,...,No,VentricularCardiomyocytes,Hst45-HEA-0-FFPE-1_window_5277,2280.637722,2885.430790,2266.702148,2901.389648,Ventricle - Compact,Cardiomyocytes,VentricularCardiomyocytes
Hst45-HEA-0-FFPE-1_oigcbndd-1,oigcbndd-1,1944.773071,2859.526367,257,0,0,0,0,0,257.0,...,No,unassigned,Hst45-HEA-0-FFPE-1_window_4464,1930.637722,2835.430790,1944.773071,2859.526367,Ventricle - Compact,Cardiomyocytes,VentricularCardiomyocytes
Hst45-HEA-0-FFPE-1_oigeiifh-1,oigeiifh-1,2077.137451,3027.821777,450,0,0,0,0,1,450.0,...,No,VentricularCardiomyocytes,Hst45-HEA-0-FFPE-1_window_4816,2080.637722,3035.430790,2077.137451,3027.821777,Ventricle - Compact,Cardiomyocytes,VentricularCardiomyocytes
Hst45-HEA-0-FFPE-1_oigenchi-1,oigenchi-1,2075.489746,2908.141357,127,0,0,0,0,1,127.0,...,NaN,unassigned,Hst45-HEA-0-FFPE-1_window_4813,2080.637722,2885.430790,2075.489746,2908.141357,Ventricle - Compact,MesenchymalCells,MesenchymalCells

In [10]:
sdata.obs

,index,cell_id,x_centroid,y_centroid,transcript_counts,control_probe_counts,genomic_control_counts,control_codeword_counts,unassigned_codeword_counts,deprecated_codeword_counts,...,fine_grain_12Jun2025,sliding_window_assignment,window_col,window_row,globalX,globalY,tt_prediction,coarse_grain_pre,coarse_grain_pre_2,coarse_grain_tacco
0,C194-HEA-0-FFPE-1_aaaenklb-1,aaaenklb-1,814.633118,1024.308105,1034,0,0,0,0,1,...,FibroblastsCOL2A1pos,C194-HEA-0-FFPE-1_window_1299,812.770691,1009.514893,814.633118,1024.308105,Adventitia - GV,MesenchymalCells,MesenchymalCells,AtrialCardiomyocytes
1,C194-HEA-0-FFPE-1_aaafjldl-1,aaafjldl-1,782.042542,977.124084,443,0,0,0,0,1,...,FibroblastsCOL2A1pos,C194-HEA-0-FFPE-1_window_1169,762.770691,959.514893,782.042542,977.124084,Adventitia - GV,MesenchymalCells,MesenchymalCells,AtrialCardiomyocytes
2,C194-HEA-0-FFPE-1_aaaifkme-1,aaaifkme-1,913.538269,1015.333435,679,0,0,0,0,0,...,PericardialCellsIntermediate,C194-HEA-0-FFPE-1_window_1557,912.770691,1009.514893,913.538269,1015.333435,Adventitia - GV,MesenchymalCells,MesenchymalCells,AtrialCardiomyocytes
3,C194-HEA-0-FFPE-1_aaamglbl-1,aaamglbl-1,849.777954,1052.411255,441,0,0,0,0,0,...,unassigned,C194-HEA-0-FFPE-1_window_1429,862.770691,1059.514893,849.777954,1052.411255,Great vessel,MesenchymalCells,MesenchymalCells,AtrialCardiomyocytes
4,C194-HEA-0-FFPE-1_aaanponc-1,aaanponc-1,854.743774,1000.949219,323,0,0,0,0,0,...,FibroblastsCycling,C194-HEA-0-FFPE-1_window_1428,862.770691,1009.514893,854.743774,1000.949219,Adventitia - GV,MesenchymalCells,MesenchymalCells,AtrialCardiomyocytes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996525,Hst45-HEA-0-FFPE-1_oigbenna-1,oigbenna-1,2148.711670,3039.862793,342,0,0,0,0,0,...,unassigned,Hst45-HEA-0-FFPE-1_window_4932,2130.637722,3035.430790,2148.711670,3039.862793,Ventricle - Compact,unclassified_mixture,unclassified_mixture,VentricularCardiomyocytes
996526,Hst45-HEA-0-FFPE-1_oigbmoed-1,oigbmoed-1,2266.702148,2901.389648,350,0,0,0,0,2,...,VentricularCardiomyocytes,Hst45-HEA-0-FFPE-1_window_5277,2280.637722,2885.430790,2266.702148,2901.389648,Ventricle - Compact,Cardiomyocytes,VentricularCardiomyocytes,VentricularCardiomyocytes
996527,Hst45-HEA-0-FFPE-1_oigcbndd-1,oigcbndd-1,1944.773071,2859.526367,257,0,0,0,0,0,...,unassigned,Hst45-HEA-0-FFPE-1_window_4464,1930.637722,2835.430790,1944.773071,2859.526367,Ventricle - Compact,Cardiomyocytes,VentricularCardiomyocytes,VentricularCardiomyocytes
996528,Hst45-HEA-0-FFPE-1_oigeiifh-1,oigeiifh-1,2077.137451,3027.821777,450,0,0,0,0,1,...,VentricularCardiomyocytes,Hst45-HEA-0-FFPE-1_window_4816,2080.637722,3035.430790,2077.137451,3027.821777,Ventricle - Compact,Cardiomyocytes,VentricularCardiomyocytes,VentricularCardiomyocytes
996529,Hst45-HEA-0-FFPE-1_oigenchi-1,oigenchi-1,2075.489746,2908.141357,127,0,0,0,0,1,...,unassigned,Hst45-HEA-0-FFPE-1_window_4813,2080.637722,2885.430790,2075.489746,2908.141357,Ventricle - Compact,MesenchymalCells,MesenchymalCells,VentricularCardiomyocytes

In [12]:
original_cell_id = 'C194-HEA-0-FFPE-1_aaaenklb-1'
sdata.obs[sdata.obs['index']==original_cell_id][['cell_id','x_centroid','y_centroid',
                                                 'coarse_grain_pre_2','coarse_grain_tacco']]

,cell_id,x_centroid,y_centroid,coarse_grain_pre_2,coarse_grain_tacco
0,aaaenklb-1,814.633118,1024.308105,MesenchymalCells,AtrialCardiomyocytes
318821,aaaenklb-1,814.633118,1024.308105,MesenchymalCells,EpicardialCells
486953,aaaenklb-1,814.633118,1024.308105,MesenchymalCells,MesenchymalCells

--> TACCO creates multiple cells on a single coordinate. Doesn't deconvolute the bin

# Save data

In [13]:
print(sdata.X.data[:10])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [15]:
# calculate QC metrices
sc.pp.calculate_qc_metrics(sdata, inplace=True)

In [17]:
del que.uns['rec'] ## Need to remove - doesn't seem to contain anything important and causes issues when saving
que.write(f'{data_object_dir}/TACCO/C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_celltype-sel_post-tacco_raw.h5ad')
print(que.shape)
sdata.write(f'{data_object_dir}/TACCO/tacco-splitted_raw.h5ad')
print(sdata.shape)

(341592, 5001)
(996530, 5001)

In [18]:
!ls -lh {data_object_dir}/TACCO

total 2.9G
-rwxrwx---+ 1 kk837 kk837 2.1G Apr 14 11:26 C194-HEA-0-FFPE-1_Hst45-HEA-0-FFPE-1_concat_5K_filtered_celltype-sel_post-tacco_raw.h5ad
-rwxrwx---+ 1 kk837 kk837 1.7G Apr 14 06:31 reference_raw.h5ad
-rwxrwx---+ 1 kk837 kk837 2.5G Apr 14 11:26 tacco-splitted_raw.h5ad

In [19]:
que

AnnData object with n_obs × n_vars = 341592 × 5001
    obs: 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'n_genes', 'tissue_block_id', 'celltypist_coarse', 'conf_score_coarse', 'celltypist_coarse_fin', 'celltypist_coarse2midmod', 'conf_score_coarse2midmod', 'celltypist_mid_fin', 'celltypist_midmod2fine', 'conf_score_midmod2fine', 'pca_harmony_leiden_0.2', 'pca_harmony_leiden_0.3', 'pca_harmony_leiden_0.4', 'pca_harmony_leiden_0.5', 'pca_harmony_leiden_0.8', 'pca_harmony_leiden_1.0', 'pca_harmony_leiden_1.5', 'pca_harmony_leiden_2.0', 'pca_harmony_leiden_3.0', 'multi_celltypes_coarse', 'fine_grain_12Jun2025', 'sliding_window_assignment', 'window_col', 'window_row', 'globalX', 'globalY', 'tt_prediction', 'coarse_grain_pre', 'coarse_grain_pre_2'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts-0', 'mean_counts-0', 'log1p_mean_counts-0', 'pct_dropout_by_counts-0', 'total_counts-0', 'log1p_total_counts-0', 'n_cells_by_counts-1', 'mean_counts-1', 'log1p_mean_counts-1', 'pct_dropout_by_counts-1', 'total_counts-1', 'log1p_total_counts-1'
    uns: 'celltypist_coarse2midmod_colors', 'celltypist_coarse_colors', 'celltypist_mid_fin_colors', 'coarse_grain_pre_2_colors', 'dendrogram_pca_harmony_leiden_1.0', 'fine_grain_12Jun2025_colors', 'multi_celltypes_coarse_colors', 'pca', 'pca_harmony', 'pca_harmony_leiden_0.2', 'pca_harmony_leiden_0.2_colors', 'pca_harmony_leiden_0.3', 'pca_harmony_leiden_0.3_colors', 'pca_harmony_leiden_0.4', 'pca_harmony_leiden_0.4_colors', 'pca_harmony_leiden_0.5', 'pca_harmony_leiden_0.5_colors', 'pca_harmony_leiden_0.8', 'pca_harmony_leiden_0.8_colors', 'pca_harmony_leiden_1.0', 'pca_harmony_leiden_1.0_colors', 'pca_harmony_leiden_1.5', 'pca_harmony_leiden_1.5_colors', 'pca_harmony_leiden_2.0', 'pca_harmony_leiden_2.0_colors', 'pca_harmony_leiden_3.0', 'pca_harmony_leiden_3.0_colors', 'tissue_block_id_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap_pca_harmony', 'spatial', 'rec', 'TACCO'
    varm: 'PCs', 'rec'
    obsp: 'pca_harmony_connectivities', 'pca_harmony_distances'